### ISSUE TITLE
Linux Firewall（firewalld）のお勉強

### ISSUE THREAD

**Issue by a-katou** [a-katou/it-note#1]
# やりたいこと
- sshも含めてアクセス元をガチガチに制御したい
- リッチルールは使いたくない
- マルチゾーンを使ってみる（使える？）

## 環境
|マシン|IPアドレス|
|-|-|
|自PC|10.0.1.254|
|サーバA|10.0.1.1|
|サーバB|10.0.1.2|

★`サーバB`にfirewalldを定義していく

### デフォルトのfirewalld設定
デフォルトのアクティブゾーンはpublic。CentOS8のデフォルトは下記。

```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

interfacesにservicesやportsを紐づけてしまうと、すべてのアクセス元からアクセスできてしまう。
sourcesにIPアドレスを追加してもアクセス元制御できない。

### とりあえずpublicゾーンからsshをはずす
```
[root@localhost ~]# firewall-cmd --permanent --zone=public --remove-service=ssh
success
[root@localhost ~]# firewall-cmd --reload
success
[root@localhost ~]# firewall-cmd --info-zone=public
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
sshを消してもなぜか既存sshセッションが切れることはない。
ただし、新規セッションは接続不可なので既存セッションを切ると二度とsshで接続できなくなる。

### このままだとサーバに新規接続できない
このままだとサーバに接続できなくなってしまうので、リッチルールを使って特定のIPアドレスからsshで接続できるようにするためのルールを追加する。

```
[root@localhost ~]# firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 source address="10.0.1.254" port port=22 protocol=tcp accept'
success
[root@localhost ~]# firewall-cmd --reload
success
[root@localhost ~]# firewall-cmd --info-zone=public
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" source address="10.0.1.254" port port="22" protocol="tcp" accept
```
これで自PCからつながるようになった。
サーバAからはつながらない。（`10.0.1.254`だけ許可しているので期待通りの動作）

#### 問題点１：ポート変更の手間
`10.0.1.1`～`10.0.1.254`に対して`22`を許可していたとする。
(`10.0.1.0/24`の1ルールで指定することもできるだが、今回のはあくまで説明用の例。)
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" source address="10.0.1.1" port port="22" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.2" port port="22" protocol="tcp" accept
　　・・・
        rule family="ipv4" source address="10.0.1.254" port port="22" protocol="tcp" accept
```

サーバBのsshポートを`22`から`50022`に変更したい場合、既存のリッチルール（`22`）254個を削除したあとに 
新しいリッチルール（`50022`）を254個登録する必要がある。

んー、スマートでない・・・(´・ω・`)

#### 問題点２：パット見でなんのルールかわかりづらい
例えば、ssh以外にもhttps（`443/tcp`）、ftp/passive（`21/tcp`、`60001-60100`）、postgresql（`5432/tcp`）、snmp（`161/udp`）を許可していたとする。
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" source address="10.0.1.1" port port="22" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.1" port port="443" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.1" port port="21" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.1" port port="60001-60100" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.1" port port="5432" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.1" port port="161" protocol="udp" accept
　　・・・
        rule family="ipv4" source address="10.0.1.254" port port="22" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.254" port port="443" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.254" port port="21" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.254" port port="60001-60100" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.254" port port="5432" protocol="tcp" accept
        rule family="ipv4" source address="10.0.1.254" port port="161" protocol="udp" accept
```

どのIPアドレスにどのポートが許可されているのかわかりづらい。

んー、スマートでない・・・(´・ω・`)

上記は手書きしたのでIPアドレス順みたく見えるが、実際は登録順、IPアドレス順、ポート順いずれにもならない（順不同）のでますます見づらくなる。

### もう少しスマートな方法はないか
サービス（ポートのグループ）単位でzoneを作成し、sources（IPアドレス）を定義してみる。

```
[root@localhost ~]# firewall-cmd --permanent --new-zone=ssh
success
[root@localhost ~]# firewall-cmd --permanent --zone=ssh --add-port=22/tcp
success
[root@localhost ~]# firewall-cmd --permanent --zone=ssh  --add-source=10.0.1.254
success
[root@localhost ~]# firewall-cmd --reload
success
```
これで自PCからつながるようになる。
サーバAからはつながらない。（期待通りの動作）

### もう少し細かく見てみる
```
[root@localhost ~]# firewall-cmd --info-zone=public
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3 enp0s8
  sources: 
  services: cockpit dhcpv6-client
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

[root@localhost ~]# firewall-cmd --info-zone=ssh
ssh (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.1.254
  services: 
  ports: 22/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
どのような動作になっているか。
ルール検証の順番は不明だが、public→sshの順に検証されたとする。
(どちらの順番でもマッチするルールがあった時点で検証は終わる。)

publicで許可されているのは全アクセス元（`interfaces: enp0s3 enp0s8`）からの`services: cockpit dhcpv6-client`のみ。
自PC`10.0.1.254`からのssh（`22`）はマッチしないので、次の`ssh`zoneに検証が移る。

sshで許可されているのは`sources: 10.0.1.254`からの[`services: cockpit dhcpv6-client`のみ](ports: 22/tcp)。
自PC`10.0.1.254`からのssh（`22`）はマッチするので、検証が終わる。

activeなzoneの分だけマッチするルールが見つかるまで検証を続ける。
マッチするルールがなければ接続不可、マッチするルールがあれば接続となる。

#### 問題点１：ポート変更の手間
マルチゾーンを使った場合sshの定義は下記となる。
```
ssh (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.1.1 10.0.1.2 ・・・10.0.1.254
  services: 
  ports: 22/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

サーバBのsshポートを`22`から`50022`に変更したい場合、`ports`の`22/tcp`を1個を削除したあとに `50022/tcp`を1個登録するだけで済む。

んー・・・(´・ω・`)

#### 問題点２：パット見でなんのルールかわかりづらい
各サービス単位でzoneを作成すると下記となる。
例えば、ssh以外にもhttps（`443/tcp`）、ftp/passive（`21/tcp`、`60001-60100`）、postgresql（`5432/tcp`）、snmp（`161/udp`）を許可していたとする。
```
ssh (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.1.1 10.0.1.2 ・・・10.0.1.254
  services: 
  ports: 22/tcp
～略～

http (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.1.1 10.0.1.2 ・・・10.0.1.254
  services: 
  ports: 443/tcp
～略～

ftp (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.1.1 10.0.1.2 ・・・10.0.1.254
  services: 
  ports: 21/tcp 60001-60100/tcp
～略～

・・・
```
zone名を工夫することで何のポートかわかりやすくなる？

んー・・・(´・ω・`)

## 結論
マルチゾーンはサービスの分だけzoneが増えるところが気にはなるが、リッチルールの気持ち悪さを経験した身からするとマルチゾーンの方がまだスマートなのかな、と感じた。

あるサービスポートを無効にしたり削除したい場合、リッチルールだと1個ずつルールを削除していかないといけないが、マルチゾーンであればゾーンに対する1操作だけで済むのでそのあたりはメリットか。
